import { Badge } from '@/types/lesson';

export const BADGES: Badge[] = [
  {
    id: 'first_step',
    title: 'Tân Binh Phù Thủy',
    description: 'Hoàn thành bài học JavaScript đầu tiên',
    icon: '🪄',
    requirement: 'Hoàn thành bài 1',
  },
  {
    id: 'eagle_eye',
    title: 'Mắt Đại Bàng',
    description: 'Thành thạo chọn phần tử trong cây DOM',
    icon: '🦅',
    requirement: 'Hoàn thành các bài về Selector',
  },
  {
    id: 'color_wizard',
    title: 'Họa Sĩ Sắc Màu',
    description: 'Làm chủ thuộc tính style và thay đổi giao diện',
    icon: '🎨',
    requirement: 'Hoàn thành các bài về Style',
  },
  {
    id: 'event_master',
    title: 'Bậc Thầy Tương Tác',
    description: 'Thành thạo bắt sự kiện click và tương tác người dùng',
    icon: '⚡',
    requirement: 'Hoàn thành các bài về addEventListener',
  },
  {
    id: 'dom_builder',
    title: 'Thợ Xây DOM',
    description: 'Biết cách tự tạo và thêm mới các phần tử HTML',
    icon: '🏗️',
    requirement: 'Hoàn thành bài về createElement',
  },
  {
    id: 'game_master',
    title: 'Lập Trình Viên Đại Tài',
    description: 'Hoàn thành dự án game Capstone đầu tay',
    icon: '👑',
    requirement: 'Hoàn thành toàn bộ lộ trình',
  },
  {
    id: 'keyboard_hero',
    title: 'Thần Gõ Phím',
    description: 'Làm chủ sự kiện bàn phím và nhập liệu theo thời gian thực',
    icon: '⌨️',
    requirement: 'Hoàn thành bài về sự kiện input',
  },
  {
    id: 'cleanup_master',
    title: 'Chuyên Gia Dọn Dẹp',
    description: 'Thành thạo xóa phần tử và làm sạch cây DOM',
    icon: '🧹',
    requirement: 'Hoàn thành bài về xóa phần tử remove()',
  },
  {
    id: 'legendary_gamer',
    title: 'Kỷ Lục Gia Game',
    description: 'Phá đảo toàn bộ các Mini-Game Capstone của vương quốc',
    icon: '🏆',
    requirement: 'Hoàn thành toàn bộ các bài tập và game',
  },
  {
    id: 'var_collector',
    title: 'Nhà Thu Thập Biến',
    description: 'Làm chủ khái niệm khai báo biến let/const và kiểu dữ liệu',
    icon: '📦',
    requirement: 'Hoàn thành bài Biến và Kiểu dữ liệu',
  },
  {
    id: 'string_operator_master',
    title: 'Bậc Thầy Chuỗi & Toán Tử',
    description: 'Thành thạo nối chuỗi Template String và các phép toán tử logic',
    icon: '🔤',
    requirement: 'Hoàn thành bài String và Toán tử',
  },
  {
    id: 'loop_logic_king',
    title: 'Vua Vòng Lặp & Logic',
    description: 'Làm chủ rẽ nhánh điều kiện If/Else và vòng lặp tự động hóa',
    icon: '🔄',
    requirement: 'Hoàn thành bài Câu điều kiện và Vòng lặp',
  },
  {
    id: 'data_structure_pro',
    title: 'Bậc Thầy Cấu Trúc Dữ Liệu',
    description: 'Thành thạo tổ chức dữ liệu với Mảng Array và Đối tượng Object',
    icon: '🎒',
    requirement: 'Hoàn thành bài Mảng Array và Đối tượng Object',
  },
];
